// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbxrbeyketznpmwjwafp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ieHJiZXlrZXR6bnBtd2p3YWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODM0NDMsImV4cCI6MjA3Mzc1OTQ0M30.c3hP1-rer5BV3oZ3Ls0yGD_N4nDzoW7vz1L3Lfv_3s8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});